services:
  db:
    image: postgres:18

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tpe_pw_test

    ports:
      - "5433:5432"

    volumes:
      - postgres_test_data:/var/lib/postgresql
      - ./db/schema/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tpe_pw_test"]
      interval: 2s
      timeout: 2s
      retries: 15

volumes:
  postgres_test_data:
