// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: avistamientos.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAvistamiento = `-- name: CreateAvistamiento :one
INSERT INTO avistamientos (
    fecha_hora,
    ubicacion,
    descripcion,
    imagen,
    hubo_destrozos,
    detalle_destrozos,
    nombre_reportante,
    email_reportante
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, fecha_hora, ubicacion, descripcion, imagen, hubo_destrozos, detalle_destrozos, nombre_reportante, email_reportante, created_at
`

type CreateAvistamientoParams struct {
	FechaHora        time.Time
	Ubicacion        string
	Descripcion      string
	Imagen           sql.NullString
	HuboDestrozos    bool
	DetalleDestrozos sql.NullString
	NombreReportante sql.NullString
	EmailReportante  sql.NullString
}

func (q *Queries) CreateAvistamiento(ctx context.Context, arg CreateAvistamientoParams) (Avistamiento, error) {
	row := q.db.QueryRowContext(ctx, createAvistamiento,
		arg.FechaHora,
		arg.Ubicacion,
		arg.Descripcion,
		arg.Imagen,
		arg.HuboDestrozos,
		arg.DetalleDestrozos,
		arg.NombreReportante,
		arg.EmailReportante,
	)
	var i Avistamiento
	err := row.Scan(
		&i.ID,
		&i.FechaHora,
		&i.Ubicacion,
		&i.Descripcion,
		&i.Imagen,
		&i.HuboDestrozos,
		&i.DetalleDestrozos,
		&i.NombreReportante,
		&i.EmailReportante,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAvistamiento = `-- name: DeleteAvistamiento :exec
DELETE FROM avistamientos
WHERE id = $1
`

func (q *Queries) DeleteAvistamiento(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAvistamiento, id)
	return err
}

const getAvistamiento = `-- name: GetAvistamiento :one
SELECT id, fecha_hora, ubicacion, descripcion, imagen, hubo_destrozos, detalle_destrozos, nombre_reportante, email_reportante, created_at
FROM avistamientos
WHERE id = $1
`

func (q *Queries) GetAvistamiento(ctx context.Context, id int32) (Avistamiento, error) {
	row := q.db.QueryRowContext(ctx, getAvistamiento, id)
	var i Avistamiento
	err := row.Scan(
		&i.ID,
		&i.FechaHora,
		&i.Ubicacion,
		&i.Descripcion,
		&i.Imagen,
		&i.HuboDestrozos,
		&i.DetalleDestrozos,
		&i.NombreReportante,
		&i.EmailReportante,
		&i.CreatedAt,
	)
	return i, err
}

const listAvistamientos = `-- name: ListAvistamientos :many
SELECT id, fecha_hora, ubicacion, descripcion, imagen, hubo_destrozos, detalle_destrozos, nombre_reportante, email_reportante, created_at
FROM avistamientos
ORDER BY fecha_hora DESC
`

func (q *Queries) ListAvistamientos(ctx context.Context) ([]Avistamiento, error) {
	rows, err := q.db.QueryContext(ctx, listAvistamientos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Avistamiento
	for rows.Next() {
		var i Avistamiento
		if err := rows.Scan(
			&i.ID,
			&i.FechaHora,
			&i.Ubicacion,
			&i.Descripcion,
			&i.Imagen,
			&i.HuboDestrozos,
			&i.DetalleDestrozos,
			&i.NombreReportante,
			&i.EmailReportante,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvistamiento = `-- name: UpdateAvistamiento :exec
UPDATE avistamientos
SET
    fecha_hora = $2,
    ubicacion = $3,
    descripcion = $4,
    imagen = $5,
    hubo_destrozos = $6,
    detalle_destrozos = $7,
    nombre_reportante = $8,
    email_reportante = $9
WHERE id = $1
`

type UpdateAvistamientoParams struct {
	ID               int32
	FechaHora        time.Time
	Ubicacion        string
	Descripcion      string
	Imagen           sql.NullString
	HuboDestrozos    bool
	DetalleDestrozos sql.NullString
	NombreReportante sql.NullString
	EmailReportante  sql.NullString
}

func (q *Queries) UpdateAvistamiento(ctx context.Context, arg UpdateAvistamientoParams) error {
	_, err := q.db.ExecContext(ctx, updateAvistamiento,
		arg.ID,
		arg.FechaHora,
		arg.Ubicacion,
		arg.Descripcion,
		arg.Imagen,
		arg.HuboDestrozos,
		arg.DetalleDestrozos,
		arg.NombreReportante,
		arg.EmailReportante,
	)
	return err
}
