// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Avistamiento struct {
	ID               int32
	FechaHora        time.Time
	Ubicacion        string
	Descripcion      string
	Imagen           sql.NullString
	HuboDestrozos    bool
	DetalleDestrozos sql.NullString
	NombreReportante sql.NullString
	EmailReportante  sql.NullString
	CreatedAt        time.Time
}
